version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go build -mod vendor .
  release:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
      - build:
  release:
    jobs:
      - release:
        filters:
          branches:
            ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
