version: 2.1
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/kontrio/kappy
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go build -mod vendor .
