version: 2.1

base_image: &base_image
  circleci/golang:1.12

working_directory: &working_directory
  /home/circleci/github.com/kontrio/kappy

repo_cache_key: &repo_cache_key
  kappy-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory
jobs:
  release:
    docker:
      - image: *base_image
    working_directory: *working_directory
    steps:
      - checkout
      - run: ./hack/goreleaser.sh
  build:
    docker:
      - image: *base_image
    working_directory: *working_directory
    steps: 
      - checkout
      - run: ./hack/goreleaser.sh --snapshot --rm-dist
      - *save_repo
      
  integration_test:
    machine: 
      image: circleci/classic:201808-01
      docker_layer_caching: true
    environment:
      GO_VERSION: 1.12.1
      K8S_VERSION: v1.14.0
      MINIKUBE_VERSION: v1.0.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
      GOPATH: /home/circleci/go
    working_directory: /home/circleci/github.com/kontrio/kappy
    steps:
      - *restore_repo
      - run:
          name: Check kappy tool built
          command: |
            ./dist/linux_386/kappy version
      - run:
          name: Install minikube
          command: |
            curl -Lo minikube https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          name: Setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          name: Start minikube
          command: |
            sudo minikube start --vm-driver=none --cpus=2 --memory=2048 --kubernetes-version=${K8S_VERSION}
            sudo mv /home/circleci/.kube /home/circleci/.minikube $HOME
            sudo chown -R $USER $HOME/.kube $HOME/.minikube
      - run:
          name: Test minikube/kubectl
          command: |
            kubectl get pods --all-namespaces
      - run:
          name: Apply testing k8s resources
          command: |
            kubectl apply -f ./test/kube-resources
      - run:
          name: Kappy Integration Test Suite
          command: |
            ./hack/integration-tests.sh
workflows:
  version: 2
  test:
    jobs:
      - build
      - integration_test:
          requires:
            - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
